import type { Metadata } from "next";
import localFont from "next/font/local";
import { Header } from './components/Header';
import { Footer } from './components/Footer';
import { Navbar } from './components/Navbar';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Núcleo Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <Navbar />
        {children}
        <p>
        <ul>
  <li>Punto 1</li>
  <li>Punto 2</li>
  <li>Punto 3</li>
  <li>Punto 4</li>
  <li>Punto 5</li>
  <li>Punto 6</li>
  <li>Punto 7</li>
  <li>Punto 8</li>
  <li>Punto 9</li>
  <li>Punto 10</li>
  <li>Punto 11</li>
  <li>Punto 12</li>
  <li>Punto 13</li>
  <li>Punto 14</li>
  <li>Punto 15</li>
  <li>Punto 16</li>
  <li>Punto 17</li>
  <li>Punto 18</li>
  <li>Punto 19</li>
  <li>Punto 20</li>
  <li>Punto 21</li>
  <li>Punto 22</li>
  <li>Punto 23</li>
  <li>Punto 24</li>
  <li>Punto 25</li>
  <li>Punto 26</li>
  <li>Punto 27</li>
  <li>Punto 28</li>
  <li>Punto 29</li>
  <li>Punto 30</li>
  <li>Punto 31</li>
  <li>Punto 32</li>
  <li>Punto 33</li>
  <li>Punto 34</li>
  <li>Punto 35</li>
  <li>Punto 36</li>
  <li>Punto 37</li>
  <li>Punto 38</li>
  <li>Punto 39</li>
  <li>Punto 40</li>
  <li>Punto 41</li>
  <li>Punto 42</li>
  <li>Punto 43</li>
  <li>Punto 44</li>
  <li>Punto 45</li>
  <li>Punto 46</li>
  <li>Punto 47</li>
  <li>Punto 48</li>
  <li>Punto 49</li>
  <li>Punto 50</li>
  <li>Punto 51</li>
  <li>Punto 52</li>
  <li>Punto 53</li>
  <li>Punto 54</li>
  <li>Punto 55</li>
  <li>Punto 56</li>
  <li>Punto 57</li>
  <li>Punto 58</li>
  <li>Punto 59</li>
  <li>Punto 60</li>
  <li>Punto 61</li>
  <li>Punto 62</li>
  <li>Punto 63</li>
  <li>Punto 64</li>
  <li>Punto 65</li>
  <li>Punto 66</li>
  <li>Punto 67</li>
  <li>Punto 68</li>
  <li>Punto 69</li>
  <li>Punto 70</li>
  <li>Punto 71</li>
  <li>Punto 72</li>
  <li>Punto 73</li>
  <li>Punto 74</li>
  <li>Punto 75</li>
  <li>Punto 76</li>
  <li>Punto 77</li>
  <li>Punto 78</li>
  <li>Punto 79</li>
  <li>Punto 80</li>
  <li>Punto 81</li>
  <li>Punto 82</li>
  <li>Punto 83</li>
  <li>Punto 84</li>
  <li>Punto 85</li>
  <li>Punto 86</li>
  <li>Punto 87</li>
  <li>Punto 88</li>
  <li>Punto 89</li>
  <li>Punto 90</li>
  <li>Punto 91</li>
  <li>Punto 92</li>
  <li>Punto 93</li>
  <li>Punto 94</li>
  <li>Punto 95</li>
  <li>Punto 96</li>
  <li>Punto 97</li>
  <li>Punto 98</li>
  <li>Punto 99</li>
  <li>Punto 100</li>
  <li>Punto 101</li>
  <li>Punto 102</li>
  <li>Punto 103</li>
  <li>Punto 104</li>
  <li>Punto 105</li>
  <li>Punto 106</li>
  <li>Punto 107</li>
  <li>Punto 108</li>
  <li>Punto 109</li>
  <li>Punto 110</li>
  <li>Punto 111</li>
  <li>Punto 112</li>
  <li>Punto 113</li>
  <li>Punto 114</li>
  <li>Punto 115</li>
  <li>Punto 116</li>
  <li>Punto 117</li>
  <li>Punto 118</li>
  <li>Punto 119</li>
  <li>Punto 120</li>
  <li>Punto 121</li>
  <li>Punto 122</li>
  <li>Punto 123</li>
  <li>Punto 124</li>
  <li>Punto 125</li>
  <li>Punto 126</li>
  <li>Punto 127</li>
  <li>Punto 128</li>
  <li>Punto 129</li>
  <li>Punto 130</li>
  <li>Punto 131</li>
  <li>Punto 132</li>
  <li>Punto 133</li>
  <li>Punto 134</li>
  <li>Punto 135</li>
  <li>Punto 136</li>
  <li>Punto 137</li>
  <li>Punto 138</li>
  <li>Punto 139</li>
  <li>Punto 140</li>
  <li>Punto 141</li>
  <li>Punto 142</li>
  <li>Punto 143</li>
  <li>Punto 144</li>
  <li>Punto 145</li>
  <li>Punto 146</li>
  <li>Punto 147</li>
  <li>Punto 148</li>
  <li>Punto 149</li>
  <li>Punto 150</li>
  <li>Punto 151</li>
  <li>Punto 152</li>
  <li>Punto 153</li>
  <li>Punto 154</li>
  <li>Punto 155</li>
  <li>Punto 156</li>
  <li>Punto 157</li>
  <li>Punto 158</li>
  <li>Punto 159</li>
  <li>Punto 160</li>
  <li>Punto 161</li>
  <li>Punto 162</li>
  <li>Punto 163</li>
  <li>Punto 164</li>
  <li>Punto 165</li>
  <li>Punto 166</li>
  <li>Punto 167</li>
  <li>Punto 168</li>
  <li>Punto 169</li>
  <li>Punto 170</li>
  <li>Punto 171</li>
  <li>Punto 172</li>
  <li>Punto 173</li>
  <li>Punto 174</li>
  <li>Punto 175</li>
  <li>Punto 176</li>
  <li>Punto 177</li>
  <li>Punto 178</li>
  <li>Punto 179</li>
  <li>Punto 180</li>
  <li>Punto 181</li>
  <li>Punto 182</li>
  <li>Punto 183</li>
  <li>Punto 184</li>
  <li>Punto 185</li>
  <li>Punto 186</li>
  <li>Punto 187</li>
  <li>Punto 188</li>
  <li>Punto 189</li>
  <li>Punto 190</li>
  <li>Punto 191</li>
  <li>Punto 192</li>
  <li>Punto 193</li>
  <li>Punto 194</li>
  <li>Punto 195</li>
  <li>Punto 196</li>
  <li>Punto 197</li>
  <li>Punto 198</li>
  <li>Punto 199</li>
  <li>Punto 200</li>
</ul>

        </p>
        <Footer />
      </body>
    </html>
  );
}
